# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: square.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'square.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csquare.proto\"\x1f\n\rSquareRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0eSquareResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32=\n\rSquareService\x12,\n\tGetSquare\x12\x0e.SquareRequest\x1a\x0f.SquareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'square_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SQUAREREQUEST']._serialized_start=16
  _globals['_SQUAREREQUEST']._serialized_end=47
  _globals['_SQUARERESPONSE']._serialized_start=49
  _globals['_SQUARERESPONSE']._serialized_end=81
  _globals['_SQUARESERVICE']._serialized_start=83
  _globals['_SQUARESERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
